### ISSUE TITLE
AlphaVantage: Wrong suffix for Stockholm

### ISSUE THREAD

**Issue by larslj** [finance-quote/finance-quote#110]
GnuCash cannot get data from the Stockholm stock exchange. The currency is missing since the suffix is incorrect in AlphaVantage.pm. The correct suffix is '.STO', e.g. ERIC-B.STO for Ericsson.

**Comment by bpschuck** [comment]
Verified issue:
`bschuck@valhalla:~$ gnc-fq-dump alphavantage ERIC-B.STO
Finance::Quote fields Gnucash uses:
    symbol: ERIC-B.STO           <=== required
      date: 04/12/2019           <=== recommended
  currency: ** missing **        <=== required
      last: 91.4000              <=\       
       nav:                      <=== one of these
     price:                      <=/        
  timezone:                      <=== optional

** This stock quote cannot be used by GnuCash!`

Can be easily fixed by a quick modification to the AlphaVantage module:
`bschuck@valhalla:~$ gnc-fq-dump alphavantage ERIC-B.STO
Finance::Quote fields Gnucash uses:
    symbol: ERIC-B.STO           <=== required
      date: 04/12/2019           <=== recommended
  currency: SEK                  <=== required
      last: 91.4000              <=\       
       nav:                      <=== one of these
     price:                      <=/        
  timezone:                      <=== optional`
