### ISSUE TITLE
Validate Fool

### ISSUE THREAD

**Issue by vincentl** [finance-quote/finance-quote#119]

**Comment by bpschuck** [comment]
@vincentl - Unless you plan on taking on all the "Validate" ToDos, perhaps share exactly what it is you're expecting for each module? Is it just a simple working/not-working? Or some level of deeper review including whether or not a not-working module can be corrected and how much effort fixing it may take? Should others assume that validating also includes updating the Modules-README.yml file? Specifying the details will also help keeping the information collected somewhat consistent.
Thanks though, I can take a few once I know how much detail to include.

**Comment by vincentl** [comment]
@bpschuck - Here is what I was thinking for each module X, but happy to make changes.

0. On the project note card for X, click in the upper right and convert to issue.  Move to in-progress.
1. If t/x.t does not exist, create one
2. Run t/x.t
2a. If test succeeds, update Modules-README.yml, close issue, and move card to done
2b. If test fails, decide how to proceed.  Start discussion on issue if you aren't sure, or fix, or remove.

Two questions about Modules-README.yml:
a. Since x.t lists the test cases, why record them in Modules-README?  It seems like it will increase the maintenance cost to make sure those two stay in sync.
b. To reconstitute a removed file, I was first thinking we would want two commits.  The first to remove and the second to update Modules-README with the commit hash.  But then I found https://stackoverflow.com/questions/7203515/git-how-to-find-a-deleted-file-in-the-project-commit-history.  Just wanted to check if anyone had additional thoughts about removing modules.

**Comment by bpschuck** [comment]
On 6/18/19 4:17 AM, vincentl wrote:

> @bpschuck <https://github.com/bpschuck> - Here is what I was thinking
> for each module X, but happy to make changes.

Just looking for clarification.

> 0. On the project note card for X, click in the upper right and 
> convert to issue. Move to in-progress.

> 1. If t/x.t does not exist, create one

While creating a test file is not that hard a task, for some of the
modules that are not for US based equities and funds, it may take a
short while to gather test cases.

> 2. Run t/x.t 2a. If test succeeds, update Modules-README.yml, close 
> issue, and move card to done

> 2b. If test fails, decide how to proceed. Start discussion on issue 
> if you aren't sure, or fix, or remove.

 As noted for HU, some pass, some fail. Multipart issue. Some fail
because the fund is no longer traded. The Hungarian equities fail
because the equities URL is no longer valid. So while one issue is
easily corrected, the other is not.

> Two questions about Modules-README.yml:

> a. Since x.t lists the test cases, why record them in
> Modules-README? It seems like it will increase the maintenance cost
> to make sure those two stay in sync.

Over the years I've found that supplying too much info is much better
than not enough. Having all the modules and test cases used in one file
makes sense to me. Just looking at one file I can run gnc-fq-dump for
multiple modules as a quick test instead of needing to look at each test
file. Come to think of it, perhaps even script it (may need to add
another field to Modules-README if the method/subroutine name doesn't
match the module name (ex: Cdnfundlibrary.pm has "fundlibrary" and
"canadamutual". Perhaps "methods:"). Taken to the extreme one could ask
why have a Modules file when you can just look in ./lib/Finance/Quote/?

> b. To reconstitute a removed file, I was first thinking we would want
> two commits. The first to remove and the second to update 
> Modules-README with the commit hash. But then I found 
> https://stackoverflow.com/questions/7203515/git-how-to-find-a-deleted-file-in-the-project-commit-history.

> Just wanted to check if anyone had additional thoughts about removing
> modules.

I'm thinking that if a once deleted module is needed again, likely a
change of source/API could mean it would be much different from the
removed module.

Here's a question mostly for Eric though. How quickly is he thinking of
uploading a new release to CPAN? And is the scope of validating all the
current modules something for a later release?

- Bruce S.

**Comment by ecocode** [comment]
@vincentl about your question a:
I like the idea of having test cases in Modules.README.  It eases searching.  i.e. once we remove a module, that info will be lost (well not completely because you can git log|grep, but who will do that?).  Keeping it in Modules.README will keep a searchable trace. We can then revive (and maybe debug) a deleted module.  However you are definitely right about problems linked to the redundancy if information.  Things can easily get out of sync.  That's why Modules-README.yml should be a generated file.  Therefor we need to first think how we should standardize our test files too.

**Comment by ecocode** [comment]
> While creating a test file is not that hard a task, for some of the modules that are not for US based equities and funds, it may take a short while to gather test cases.

Create the test file with basic template.  It is a first step if the file is missing :)
Thinking about this item, we should create a test which looks if every module has a test-file..

> As noted for HU, some pass, some fail. Multipart issue. Some fail because the fund is no longer traded. The Hungarian equities fail because the equities URL is no longer valid. So while one issue is easily corrected, the other is not.

For the next release, I'd like all test files scanned and all failing tests encapsulated in a TODO:{} block.  Besides the fact that a succeeding test-suite feels great ;), TODO-blocks will start shouting if failing tests start to succeed.  So don't delete tests just for failing, cos maybe things can start working again and it is good to see that happen.  For info TODO:{} feature comes from Test::More.

> Here's a question mostly for Eric though. How quickly is he thinking of uploading a new release to CPAN? And is the scope of validating all the current modules something for a later release? - Bruce S.

Let me put myself a deadline here: I commit to get it out next weekend :)
But it would certainly be cool to have a clean test-suite (failing tests marked TODO) if possible...

**Comment by bpschuck** [comment]
On 6/18/19 8:31 AM, Erik Colson wrote:

> That's why Modules-README.yml should be a generated file. Therefor we
> need to first think how we should standardize our test files too.
I'm just say'n, but it might be just a bit difficult to generate a
section in Modules-README.yml for a module that doesn't exist because it
was deleted. ;)

Process would need to retain modules marked at removed/deleted.

But I do love the idea of trying to keep a standardized style/template
for test files.

- Bruce S.

**Comment by bpschuck** [comment]
On 6/18/19 8:49 AM, Erik Colson wrote:

> Create the test file with basic template. It is a first step if the
> file is missing :)

> Thinking about this item, we should create a test which looks if
> every module has a test-file..

Should be easy.

> For the next release, I'd like all test files scanned and all
> failing tests encapsulated in a TODO:{} block. Besides the fact that
> a succeeding test-suite feels great ;), TODO-blocks will start
> shouting if failing tests start to succeed. So don't delete tests
> just for failing, cos maybe things can start working again and it is
> good to see that happen. For info TODO:{} feature comes from
> Test::More.

I'll take a look at hu.t since I already know some of the issues with
it. Not sure why I started looking at in the first place, I think it's
because it's the one I noticed throw many errors when I set ONLINE_TEST
and ran make test.

> Let me put myself a deadline here: I commit to get it out next
> weekend :) But it would certainly be cool to have a clean test-suite
> (failing tests marked TODO) if possible...
Checking 60 test files may be a just a little ambitious for a release
this coming weekend, or by "next" do you mean the 28th-29th time-frame?

- Bruce S.

P.S. - I really should get some work done at my day job... ;)

**Comment by ecocode** [comment]
> I'm just say'n, but it might be just a bit difficult to generate a section in Modules-README.yml for a module that doesn't exist because it was deleted. ;)

lol,  good point !

> Process would need to retain modules marked at removed/deleted.

Or moving deleted modules into ModulesDeleted-README.yml

> But I do love the idea of trying to keep a standardized style/template for test files.

Yes, getting consistency into all levels seems to simplify maintenance problems.

**Comment by ecocode** [comment]
> Checking 60 test files may be a just a little ambitious for a release this coming weekend, or by "next" do you mean the 28th-29th time-frame? 

Nope, I mean 22-23 february..
It won't harm if there is still some work to do on the test-files, all releases till now have been faulty, so nobody will notice a difference :)  And there is nothing against another release a few weeks later.

- Bruce S. P.S. - I really should get some work done at my day job... ;)

**Comment by bpschuck** [comment]
On 6/18/19 11:12 AM, Erik Colson wrote:

> Nope, I mean 22-23 february..

Well that changes things a bit being a tad more than a week away. ;)

> It won't harm if there is still some work to do on the test-files,
> all releases till now have been faulty, so nobody will notice a
> difference :) And there is nothing against another release a few
> weeks later.
Kind of my feeling as well. No harm in stretching it out over the next
couple releases. It's not as if people are reporting issues with all the
modules that are probably no longer working.

- Bruce S.

**Comment by bpschuck** [comment]
On 6/18/19 11:06 AM, Erik Colson wrote:

> Process would need to retain modules marked at removed/deleted.

> Or moving deleted modules into ModulesDeleted-README.yml

My preference would be one file and when generated keep the modules
marked as removed/deleted.

>> But I do love the idea of trying to keep a standardized 
>> style/template for test files.

> Yes, getting consistency into all levels seems to simplify 
> maintenance problems.

Slightly off topic, I'll try to be brief.

My first real job after graduating university there was an occasion
where my boss and I were troubleshooting a bug in a "C" program. Wanting
to quickly solve the problem I was kind of annoyed when he spent about
the first 40 minutes doing nothing but reformatting the code (indents,
if for and while blocks, etc) when we sat down together to find the
issue. Fast forward a number of years and I had to modify a somewhat
lengthy bash script written by someone else and fix some minor bugs in
it. Wouldn't you know it, in order make heads or tails of some of its
logic, I had to spend about 30 minutes reformatting it before I could do
any real changes. :)

- Bruce S.

**Comment by ecocode** [comment]
> My preference would be one file and when generated keep the modules marked as removed/deleted.

I agree

> I had to spend about 30 minutes reformatting it before I could do any real changes. :)

Frustrations are base requirements to get into two of most important human assets: experience and patience ;)
FYI: in Perl there is Perl::Tidy which does an awesome job at reformatting code.  If you configure your editor to use it, you can even use perltidy to reformat part of a file if you don't want to reformat all of it.

**Comment by vincentl** [comment]
I just pushed a commit for TSP.pm that included manual updates to Modules-README.yml.  I thought that it would be helpful to have some validation data whenever we settle on a generation method for Modules-README.yml.

**Comment by vincentl** [comment]
There are two options to revive Fool.pm:

1. Use http://caps.fool.com/Ticker/AAPL.aspx to query the community stock pick site once per ticker symbol

2. Use https://www.fool.com/quote/nyse/rht/rht/ to query Fool news-centric pages.  Also one query per ticker symbol and we need to know if it is nyse or nasdaq (which might really mean 2 queries to see which succeeds).

**Comment by bpschuck** [comment]
On 6/18/19 7:50 PM, vincentl wrote:

>  2.

>     Use https://www.fool.com/quote/nyse/rht/rht/ to query Fool
>     news-centric pages. Also one query per ticker symbol and we need to
>     know if it is nyse or nasdaq (which might really mean 2 queries to
>     see which succeeds).

Don't forget about the AMEX exchange. My thinking is choice 1 might be
better since it doesn't matter what exchange.

- Bruce S.
