### ISSUE TITLE
ASX Quotes - Unrounded values being returned

### ISSUE THREAD

**Issue by Pedro288** [finance-quote/finance-quote#127]
since about 1 Jul ASX quotes haas been returing a random selection of quote values of the dollar figure, a + sign and a string of numbers.  see image
![aagnu2](https://user-images.githubusercontent.com/53068981/61506203-b7c20080-aa24-11e9-8f62-966a3f850a2e.JPG)
![AAGNU](https://user-images.githubusercontent.com/53068981/61506204-b7c20080-aa24-11e9-880c-2a8b2ce2c355.JPG)

Workaround so far is to manually edit

**Comment by goodvibes2** [comment]
Hi Pedro,
I think this is a GnuCash problem, not Finance::Quote.
See still unfixed problem https://bugs.gnucash.org/show_bug.cgi?id=797106.
You can confirm this by using gnc-fq-dump or gnc-fq-helper
See 
https://wiki.gnucash.org/wiki/FAQ#Q:_Why_doesn.27t_online_quoting_work.3F
and
https://wiki.gnucash.org/wiki/FAQ#Q:_How_do_I_fix_a_.22system_error.22_or_.22unknown_error.22_when_getting_stock_quotes.3F
Note you are probably using Finance::Quote price source Yahoo as JSON (yahoo_json) or Alphavantage US (alphavantage) rather than "Australian Stock Exchange" (asx) as the asx website was modified around Feb 2018 to always require JavaScript, so as far as I know, there is no way it can be used with F::Q.

**Comment by bpschuck** [comment]
Thank you Chris for explaining the issue/bug in GnuCash.
If it's okay with the other F::Q maintainers, I will close this issue in a day or two unless one of you object.

**Comment by ecocode** [comment]
Hi
I close this issue now.  If needed it can be reopened.

**Comment by Pedro288** [comment]
Erik,

Sorry have been away.
From further research it appears that the issue is related to:
a.  the display of value in the Tool>Price Database pop up window and
b. The Advanced Portfolio report

As previously advised on using the Price Database to Get quotes, some (not all) share prices are returned with a value the shows in Price Database as “nn +nnnnnnnnnnn”.
Upon Reload of the Advanced Portfolio (see pic below)




If the Reload is then applied to the Advanced Portfolio report the random numbers also appear, see pic below

I then return to the Price Database and manually correct the faulty entries and Reload.  However, I have noticed while the random Price entries are a distraction the underlining value is correct as the Advanced Portfolio Value Column in this example above ($580390.22) remains the same.. i.e. even though the prices displayed are askew the real value is correctly applied (except in the Price Database and the Advanced Portfolio report.



Regards

Peter
