### ISSUE TITLE
"Makefile.PL": No such file

### ISSUE THREAD

**Issue by mingwugmail** [finance-quote/finance-quote#135]
The install instruction says:

```
perl Makefile.PL
make
make test
make install
```

But there is no such file Makefile.PL

```
$ perl Makefile.PL
Can't open perl script "Makefile.PL": No such file or directory
```

**Comment by bpschuck** [comment]
The install instructions in README.md are specific to install from a release tarball downloaded from CPAN. The latest release can be downloaded from https://www.cpan.org/authors/id/E/EC/ECOCODE/Finance-Quote-1.49.tar.gz.
You may also wish to read the Hackers-Guide in the Documentation folder.
Related to this is the reference to the INSTALL file which does not currently exist.
Thank you.

**Comment by bpschuck** [comment]
Addressed in merged pull request #136.

**Comment by rdegraaf** [comment]
I need a fix for a bug that you resolved over a year ago (https://github.com/finance-quote/finance-quote/issues/114), but you haven't made a release to CPAN since then. And I'm not familiar with whatever development tools that you use, so I haven't been able to install the current development version from source.

If you're not ready to make a new release, can you describe what we need to do to install from source?  Or if you're purposefully not doing that because the current development version is not usable, do you know when we can expect a new release?

**Comment by vincentl** [comment]
Hi,

We are close to release version 1.50 of Finance::Quote.

I posted a release candidate at
https://github.com/finance-quote/finance-quote/releases/tag/v1.50-rc.1 that
you can use to install.  If you test out the release candidate and find any
bugs, please open an issue at
https://github.com/finance-quote/finance-quote/issues

Best,

Vince
