### ISSUE TITLE
Remove Modules-README.yml

### ISSUE THREAD

**Issue by vincentl** [finance-quote/finance-quote#162]
I'm finding the Modules-README.yml too difficult to keep updated properly with respect to the code base.  Since git can answer questions like when was a module added or removed and the testes are self documenting, I'm not sure I see enough value considering the overhead of keeping it up to date.

Thoughts?

**Comment by bpschuck** [comment]
Going back to conversation last June (2019) that was the impetus of the file being created, I believe it is still handy. To quite @ecocode from back then:

> I like the idea of having test cases in Modules.README. It eases searching. i.e. once we remove a module, that info will be lost (well not completely because you can git log|grep, but who will do that?). Keeping it in Modules.README will keep a searchable trace. We can then revive (and maybe debug) a deleted module. However you are definitely right about problems linked to the redundancy if information. Things can easily get out of sync. That's why Modules-README.yml should be a generated file.

For the current scope, it is a handy place to quickly indicate which modules are candidates for removal since quite a few no longer work or their functionality is now best served by another module.

As a personal rant, after 35 some odd years in the IT biz and having worn many different hats in that time, I always cringe when a coworker doesn't want to do something because "it adds more work". Unfortunately, that comment is more often than not about documentation.

**Comment by vincentl** [comment]
I'm happy to take a crack at auto-generation.  I let you know how it goes.

**Comment by jvolkening** [comment]
Another use for this file may be to allow for broken modules to exist without preventing successful builds/releases. Perhaps the modules still have perceived utility and may be fixed in the future.

I would envision that the file could be parsed, and the files for modules not listed as 'working' could be added to a pruning list in the `dist.ini` file. I have contributed to other projects that, like this one, contain heterogeneous modules of code depending on upstream data/service/code sources, some fraction of which tend to be broken at any given time as the upstream sources change or break or die. Those projects have made use of a blacklist of some sort that both excludes the broken pieces from the build process and provides a place for contributors to look to find things to work on.

**Comment by jvolkening** [comment]
Can I suggest a `deprecated` boolean field in the `Modules-README.yml` entries? This would indicate modules which perhaps still work but which are entirely superseded by other more general or more robust modules. Such modules would likely be removed if broken in the future.

**Comment by bpschuck** [comment]
On 10/11/20 8:26 PM, Jeremy Volkening wrote:

> Can I suggest a |deprecated| boolean field in the
> |Modules-README.yml| entries? This would indicate modules which
> perhaps still work but which are entirely superseded by other more
> general or more robust modules. Such modules would likely be removed
> if broken in the future.
It is a YAML file that was thrown together, adding an additional field 
is not a problem. On the other hand, noting a module is deprecated and 
other modules will satisfy its function can be indicated in the "notes" 
field and/or the "state" field.

Thanks.

- Bruce S.

**Comment by ecocode** [comment]
> I'm happy to take a crack at auto-generation. I let you know how it goes.

Hi vincent,  About this auto-generation... I think we should not regenerate the entire file, but instead update the file with info that can be obtained from the individual module files.  i.e. this would help to keep a trace of modules which were removed.  I would find it handy to have a script which goes as follows:
- check for every module if some data needs to be updated.
- for each module which requires data update:
  1. show data to be updated
  2. ask the user if he is ok with the changes to be applied, and then apply them

The script could also be used as a test (with a flag), so we know if the data-file needs to be updated.

**Comment by bpschuck** [comment]
Awesome idea Erik! Sometimes a hybrid of auto/manual makes better sense.

Sorry I have been not as active lately. Aside from work and some side
contract work, I have volunteered to help out the good folks at
https://cacert.org/ remotely. Felt odd going through an interview
process for a job I'm volunteering for, but it's all good.

- Bruce S.

**Comment by ecocode** [comment]
congrats for the job :+1: 
what will you be responsible for ?

**Comment by bpschuck** [comment]
On 10/24/20 15:03, Erik Colson wrote:

> congrats for the job 👍

Thanks!

> what will you be responsible for
Backend systems. Email, Puppet, Gitlab, Wiki, etc. The web facing and
Certificate Authority systems are managed by another team within CA Cert.

It's not exactly a job, as there is the same "contribute when you can"
as most opensource projects. But I've been a long time proponent of
email encryption and signing using PGP/GnuPG or S/MIME. Probably since
the early to mid 1990s.

- Bruce S.

**Comment by ecocode** [comment]
sounds awesome!  I used email encryption in the 90's too, but eventually stopped using it...

**Comment by vincentl** [comment]
Still working on PRs and then I will write the YAML tool.  That's what I had in mind - something that will highlight inconsistencies or missing info so we can work through those module by module.

**Comment by jvolkening** [comment]
Since I am new here, I'm very hesitant to start going at things with a hatchet. However, my inclination, given how many broken modules there are, would be to start going through each module and see if it provides data for any securities not provided by more general-purpose sources. If not, I would mark it for removal and/or actually remove it from the source tree. This would allow a focus on fixing the most needed modules in order to work toward a new release.

In addition, for modules that are wanted but not easily fixed, I would mark them as broken in the `Modules-README.yml` and then add them to a pruning section in the `dist.ini`. I wrote a simple script to parse the YAML and update the INI, and it ends up looking something like this in the INI file:

```ini
[PruneFiles]
filename = DEV-RELEASE-INFO.org ; stuff todo
filename = dist.ini ; Dist::Zilla config file not needed in release
filename = GPATH
filename = GRTAGS
filename = GTAGS
filename = lib/Finance/Quote/ASEGR.pm ; failing/obsolete/removed
filename = t/asegr.t ; failing/obsolete/removed
filename = lib/Finance/Quote/BMONesbittBurns.pm ; failing/obsolete/removed
filename = lib/Finance/Quote/BSERO.pm ; failing/obsolete/removed
filename = lib/Finance/Quote/Bloomberg.pm ; failing/obsolete/removed
filename = lib/Finance/Quote/Bourso.pm ; failing/obsolete/removed
filename = t/bourso.t ; failing/obsolete/removed
filename = lib/Finance/Quote/CSE.pm ; failing/obsolete/removed
filename = lib/Finance/Quote/Cdnfundlibrary.pm ; failing/obsolete/removed
filename = t/cdnfundlibrary.t ; failing/obsolete/removed
# etc...
```
The philosophy behind this is that, because the current release can and does break without any change to the code base (due to broken/changed data sources), it does not make sense to hold up new releases waiting for every broken module to be fixed. Rather, new releases should be pushed whenever a module that is broken in the current production release has been fixed. This is just my philosophy, and if it's at odds with the prevailing thinking in the project, that's fine.

**Comment by ecocode** [comment]
Hi Jeremy!

I didn't see you joined the team.  This is awesome news!

I am OK with removing broken modules.  While doing so, please pay special attention to group module removal in a specific commit which contains:
- Quote.pm: removal of the module reference
- the specific module .pm to be removed
- the specific test files for it
- Modules-README.yml: marking the module as removed
- anything else related ?

Also mention the exact module name and the word "removed" in the commit (like "removed module FooBar").
So, it can easily be retrieved and reactivated if ever needed, with only one commit to revert.

On the other hand, I don't feel 100% comfortable pruning modules from the releases from within dzil.ini.  I got 3 reasons for this:
- Broken modules do not brake a release because no module tests are run at installation on a user machine.
- People might find the module through the github repo, and then will be surprised it isn't included in the release for a weird reason they might not understand.  Even if broken, they might want to fix it.
- It happened in the past that a module was broken for some time, then magically worked again.  In this case, users would have to downgrade F::Q till a new release is uploaded (which doesn't happen quite often ;))

It is true this didn't happen often, and your idea follows the path of cleaning the codebase (which is really a must).
So, it is a 50/50 to me :)

@vincentl , @bpschuck : your idea about this ?

**Comment by ecocode** [comment]
@jvolkening  Sorry, I was too fast.  You are a member, but not part of team (yet)..  Do you want to join?

**Comment by bpschuck** [comment]
Erik,

It's been some months since we all heard from you. I hope that all is
well and there no serious issues that prevented you from communicating.

Please drop us a note.

- Bruce S.

**Comment by bpschuck** [comment]
Seems the consensus is that at least for the time being the Modules-README.yml file is not to be removed.
Can we close this issue?

**Comment by bpschuck** [comment]
Closing. At least for time being, Modules-README.yml is not being removed.
