### ISSUE TITLE
quotes for Canadian Mutual Funds

### ISSUE THREAD

**Issue by andrew521** [finance-quote/finance-quote#175]
I have tried a couple of providers (bmonesbittburns, canadamutual, fundlibrary) but none of them seems to be working.  More details [here](http://gnucash.1415818.n4.nabble.com/GNC-Online-quotes-for-Canadian-Mutual-Funds-td4724932.html).

Any suggestions?

**Comment by vincentl** [comment]
We are working on at 1.50 release and for that release:

- BMONesbittBurns.pm was removed because the site changed significantly
- Fundata.pm that provides canadamutual was updated
- Cdnfundlibrary.pm that provides fundlibrary hasn't changed

I just ran the module tests for Fundata.pm and Cdnfundlibrary.pm and they both passed for the 1.50 release candidate.  Since there hasn't been change to Cdnfundlibrary.pm, I'm concerned our tests aren't sufficient.

If bmonesbittburns provides unique information not covered by other modules, please open a new issue just for that source and we can revisit updating that module.

For the other two modules, one option is to install https://github.com/finance-quote/finance-quote/releases/download/v1.50-rc.1/Finance-Quote-1.50.tar.gz and see if canadamutual & fundlibrary work for you.

**Comment by andrew521** [comment]
Thank you Vincent. How do I install it on Windows from the tar.gz file?

**Comment by ThierryLes** [comment]
Unpack it (using software like 7zip: unpack "Finance-Quote-1.50.tar.gz" , it create ""Finance-Quote-1.50.tar" unpack it), and then copy all the files in your Perl installation folder, something like "C:\Strawberry\perl\site\lib\Finance"

**Comment by andrew521** [comment]
I had to manually install Web::Scraper, Spreadsheet::XLSX and HTML::TokeParser::Simple and now it works. Tremendous gratitude.

D:\tools\gnucash\bin>perl D:\tools\gnucash\bin\gnc-fq-dump -v fundlibrary  TDB902
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/window[.]dataSourceResults=({ <-- HERE .+})</script>/ at D:/tools/Strawberry/perl/site/lib/Finance/Quote/HU.pm line 102.
Finance::Quote fields Gnucash uses:
    symbol: TDB902               <=== required
      date: 03/02/2021           <=== recommended
  currency: CAD                  <=== required
      last: 87.10                <=\
       nav: 87.10                <=== one of these
     price: 87.10                <=/
  timezone:                      <=== optional

All fields returned by Finance::Quote for stock TDB902

stock           field  value
-----           -----  -----
TDB902       currency: CAD
TDB902           date: 03/02/2021
TDB902        isodate: 2021-03-02
TDB902           last: 87.10
TDB902           link: https://www.fundlibrary.com/MutualFunds/GetFundSearchResults?cifscCategoryId=0&fundCompanyId=0&fundTypeId=0&isGradeA=true&isGradeB=true&isGradeC=true&isGradeD=true&isGradeE=true&sortBy=Default&page=0&searchText=TDB902
TDB902         method: fundlibrary
TDB902           name: TD U.S. Index Fund e-Series
TDB902            nav: 87.10
TDB902            net: -0.47%
TDB902       p_change: 10.09%
TDB902          price: 87.10
TDB902         source: http://www.fundlibrary.com
TDB902        success: 1
TDB902         symbol: TDB902
TDB902          yield: -0.47%

**Comment by vincentl** [comment]
Glad to hear it is working for you. I'm going to close this issue, but if you find any issues with the 1.50 release candidate, please open a new issue.

**Comment by andrew521** [comment]
Vincent,

I cannot get online quotes anymore for currencies after installing 1.50rc1. Is this a known bug?

**Comment by ThierryLes** [comment]
Yes, issue Finance Quote 1.50 RC1 - Issue with Currency & Quote.pm file. (#173).
You can temporary go around by downloading the previous version (1.49), and use the old "Quote.pm" file instead of the one from 1.50RC1.
