### ISSUE TITLE
Trustnet service not available

### ISSUE THREAD

**Issue by pipashf** [finance-quote/finance-quote#228]
Trustnet service not available for quotes - using latest Finance::Quote with GNUCash the two options for Trustnet UK is greyed out.

**Comment by bpschuck** [comment]
The Trustnet module was removed from F::Q due to changes in the site. Pricing data was no longer available.
In the future, please specify the specific F::Q version. The latest version is v1.52. This may not be the "_latest_" available from OS repositories (for example, if you have Ubuntu 22.04LTS, v1.51 will be the latest version available through apt-get).

**Comment by bpschuck** [comment]
That said, I am going to close this issue unless someone volunteers to find out if the data is still available **and** rewrite the module.

**Comment by bpschuck** [comment]
Closing issue, Trustnet no longer has a public API.
