### ISSUE TITLE
How to make the module from source?

### ISSUE THREAD

**Issue by Kaligula0** [finance-quote/finance-quote#233]
How to "make" the updated module F::Q myself from GitHub source? Now we're waiting for the next release with bugfix (for Alphavantage) but such manual can be helpful also for somebody in the future :)
(I admit, I'm only a hobbist programmer – I don't know Perl, but with the help of the Internet I've made a lot of scripts in many programming languages, so that's not a big problem.)

**Comment by Kaligula0** [comment]
I'm not sure if the manual written by the [Release](https://github.com/finance-quote/finance-quote/releases/tag/v1.52) is sufficient, because I see that some files from the .tar.gz are missing here in the repo.
Moreover, I'm running Windows. Is it necessary to use Linux?

**Comment by bpschuck** [comment]
Sorry, but there was a death in the family last month requiring me to travel out of state for a few weeks. Being a co-executor and co-trustee for the estate, the bulk of my free time has been consumed with family business. On top of that, Hurricane Ian made landfall just about right on top the deceased's home with a possible 12 to 18 foot storm surge coming later.

That said, the Release.md file is more of a checklist for the maintainers when pushing a new release to CPAN. Related to that is the tarballs contain some files automatically generated by [Dist::Zilla](https://dzil.org/) need for CPAN.

Personally I have not tried using Dist::Zilla on a MS Windows system. Myself and the other maintainers primarily use Linux/Unix systems for F::Q development. But once installed correctly Dist::Zilla should work just as well on MS Windows as it does on Linux/Unix. Note, that you would not execute `dzil release` since write access to both the CPAN F::Q namespace and the F::Q Github repo is necessary, but instead `dzil build` will create a tarball with the familiar makefile.PL used for manual Perl Module installs.

Again, sorry to you and anyone else reading this for the delay.

- Bruce S

**Comment by Kaligula0** [comment]
I'm very sorry for the situation in your family :( My condolences.
I didn't mean to create pressure on you, that's why I asked for instructions (for future generations) on how to build from source by myself, not for ETA of new release.

Speaking about the module. Thanks to your advice I managed to update the module on my computer to the current GitHub state!

If I understand the process correctly it goes like this:
1​) GitHub source code gets several checks and changelog/docs updates
2​) Release is built using Dist::Zilla `dzil build`
Then either
3​) Release is published on CPAN
4​) Module gets installed using `cpan Finance::Quote`.
or
3​) Release is published somewhere else, e.g. GitHub
4​) Manual install:
 4a) download the release
 4b) unpack it
 type those 3 commands (CLI) in the main directory of the unpacked archive:
 4c) `perl Makefile.PL`
 4d) `make`
 4e) `make install`

I use Windows 7 with Strawberry Perl and don't have Dist::Zilla. I wanted to omit installing/learning the Dist::Zilla so I decided to omit the step 1) (it's not necessary for private emergency use when waiting for official release) and tried updating files in the already 'dzil-built' release (like cracking old games, huh?), so I also omitted step 2).

So I did this:
- instead of steps 1-4b) for current release
I think that cpan downloads the release `.tar.gz` into `%PERL_DIR%\cpan\sources\authors\id\B\BP\BPSCHUCK\Finance-Quote-1.52.tar.gz` then extracts it to `%PERL_DIR%\cpan\build\Finance-Quote-1.52-0`, so the 'dzil-built' files are already on disk. Here we are at step 4b) of the currently installed version of Finance::Quote.
- instead of steps 4a-b) for new version
I downloaded the source from GitHub and unpacked (somewhere, e.g. desktop). Then copied just the `/lib` directory from source into the `%PERL_DIR%\cpan\build\Finance-Quote-1.52-0` directory.
- step 4c)
I double-clicked the `Makefile.pl`. It should run automatically – if not, then `perl Makefile.pl` in CLI, from the `%PERL_DIR%\cpan\build\Finance-Quote-1.52-0` directory.
- step 4d)
Neither Windows nor Strawberry Perl has `make.exe`, but Strawberry Perl has `gmake.exe` that works the same. So use command `gmake` from the same directory.
- step 4e)
As above – run `gmake install`.

I don't know if it's clear enough, but you can make a doc out of it and link here for any questions.

**Comment by bpschuck** [comment]
While it's appreciated, with Perl there is usually a few ways to accomplish something (Larry Wall, Perl's creator used to say that all the time). People versed in Perl may play with setting the PERL5LIB environment variable or otherwise changing the value of `@INC` to avoid possibly corrupting modules installed normally. So thanks, but your suggestion is appreciated but is not going to be incorporated at this time.

- Bruce S
