### ISSUE TITLE
AlphaVantage.pm divides both GBP & GBX by 100

### ISSUE THREAD

**Issue by Wm-X** [finance-quote/finance-quote#281]
around line 279 in AlphaVantage.pm it says 
`# divide GBP quotes by 100`
the code then does this test
`if ( ($info{ $stock, 'currency' } eq 'GBP') || ($info{$stock,'currency'} eq 'GBX') ) {`
which is wrong

the test should be
`if ($info{$stock,'currency'} eq 'GBX') {`
or the line below using GBp (not GBP)

it is possible the confusion in the original code arose because GBp (note capitalisation vs GBP) is sometimes used for prices in whole pennies, so maybe the original intention was 

`# divide GBp quotes by 100 # <-- note GB[pP] case`
`if ( ($info{ $stock, 'currency' } eq 'GBp') || ($info{$stock,'currency'} eq 'GBX') ) { # <-- note GB[pP] case`

Edit: I didn't mean to shout, no idea why the wiki stuff is showing as LOUD

From https://en.wikipedia.org/wiki/Pound_sterling:

"The ISO 4217 currency code for sterling is "GBP", formed from the [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code for the United Kingdom, "GB", and the first letter of "pound". Stock prices are often quoted in pence, so traders may abbreviate the penny as GBX (sometimes GBp) when listing stock prices."

**Comment by bpschuck** [comment]
It would be *extremely* helpful to include example securities to be used to test any changes.
Thank you.

**Comment by Wm-X** [comment]
No, just fix it.  It used to work, someone broke it.  No need for discussion

**Comment by bpschuck** [comment]
Issue placed on hold until further details are supplied.

**Comment by Wm-X** [comment]
I have proposed fixing it before and got ignored.  I did all the homework then.  I hate lazy people

**Comment by Wm-X** [comment]
Why on hold?  IT IS BROKEN

**Comment by Wm-X** [comment]
If something is broken, why don't you just fix it?

**Comment by bpschuck** [comment]
On hold because I had a simple request, "It would be extremely helpful to include example securities to be used to test any changes."
Perhaps you need to be reminded that no one is paid to contribute to F::Q. Most, if not all, **volunteer** their free time to fix bugs, add features, etc. 
So instead of just indicating a few symbols to test with, you want to act like a 5 year old child having a tantrum because mommy won't buy you a toy.
Me, I have a simple adage when it comes to people requesting help, "help me help you". If I need assistance I help those I ask help me.

**Comment by bpschuck** [comment]
Introduced in commits bfb7cf24 and e3233656.

Part of v1.45 release.

```
commit d31457890638c52f038a05f8014890d070f0aca4
Author: Erik Colson <eco@ecocode.net>
Date:   Wed Nov 8 21:36:41 2017 +0100

    v1.45

            * alphavantage
              * more suffix - currency pairs added
              * GBP and GBX divided by 100
```

**Comment by bpschuck** [comment]
I don't believe it ever worked. As the AlphaVantage module was added around the time of the above commits after the Google JSON API went dark.

Why did I want examples, so not being familiar with UK securities I didn't have waste time looking for examples to see what the AlphaVantage API returns.  For example the symbols `GBP.L` and `GBPG.L`.  The AlphaVantage API (https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=GBPG.L&apikey=XXXXXXXX) does **not**  include a currency in the output as seen here:

```
% curl "https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=GBPG.L&apikey=${ALPHAVANTAGE_API_KEY}"
{
    "Global Quote": {
        "01. symbol": "GBPG.L",
        "02. open": "43.1900",
        "03. high": "43.1900",
        "04. low": "43.0840",
        "05. price": "43.0950",
        "06. volume": "23330",
        "07. latest trading day": "2023-05-26",
        "08. previous close": "43.0675",
        "09. change": "0.0275",
        "10. change percent": "0.0639%"
    }
}
```

Because of this, the module uses a hash to map extensions to currencies. The `.L` maps to `GBP`. The problem is that `GBPG.L` is traded in GBP, and `GBP.L` is GBp (aka GBX). A fix is more than changing one line. It would necessitate also calling AV's `SYMBOL_SEARCH` API which returns the currency for a given symbol:

```
% curl 'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=GBP.L&apikey=FOOBAR&datatype=json'
{
    "bestMatches": [
        {
            "1. symbol": "GBP.LON",
            "2. name": "Global Petroleum Limited",
            "3. type": "Equity",
            "4. region": "United Kingdom",
            "5. marketOpen": "08:00",
            "6. marketClose": "16:30",
            "7. timezone": "UTC+01",
            "8. currency": "GBX",
            "9. matchScore": "1.0000"
        }
    ]
}
```

That introduces its own problem as the AV module is forced to throttle API calls to 5 per minute because of the AlphaVantage's limitations on using the free API key. For UK securities that would need 2 queries per symbol, that comes down to just 2 stocks per minute.

**Comment by Wm-X** [comment]
testing to see if we are still waving hands at each other

**Comment by Wm-X** [comment]
Alphavantage.pm is still wrong, please, try being a human with an undertstanding of decimals an read this
===

                # divide GBP quotes by 100
                if ( ($info{ $stock, 'currency' } eq 'GBP') || ($info{$stock,'currency'} eq 'GBX') ) {
                    foreach my $field ( $quoter->default_currency_fields ) {
                        next unless ( $info{ $stock, $field } );
===
you are dividing (in USA terms) a whole unit of currency (USD1) and a hundredth of the currency by the same amount.

Why can't you see the MATHS is wrong ?

**Comment by Wm-X** [comment]
I don't know what to do with someone that doesn't understand that dividing 1 cent or 1 pence by 100 will result in a number a few decimals wrong.  Just baffled

**Comment by Wm-X** [comment]
Putting this back on hold is NOT going to solve the problem of a HUMAN not being able to read and understand

**Comment by Wm-X** [comment]
if you want some fun, you could try VEMT.L as it has switched

**Comment by Kaligula0** [comment]
> Because of this, the module uses a hash to map extensions to currencies. The `.L` maps to `GBP`.

Wait wait. I don't use AlphaVantage.pm and am out of home now so can't check it, but this seems like a bad idea. Look at the MVOL.L or ISLN.L – they are in USD!

**Comment by bpschuck** [comment]
@Kaligula0,

Thanks for pointing that out! It sheds more light on the issue at hand.

The currency map has been in place since the module was originally written since the quote API does **not** include a currency. Shortly afterwards Erik added the correcting when he or someone noticed that some LSE stocks are traded in GBX/GBp and not GBP. I reached out to AlphaVantage asking if they could include the traded currency in the JSON returned by the API and their answer:

"Hi Bruce, thanks for the feature request. We will ask our upstream data partner whether they can license us to modify the JSON schema to include the currency info. Thank you!"

Unfortunately this is pretty much the same answer I was given to other requests in the past that were never fulfilled.

This goes back to my comment (https://github.com/finance-quote/finance-quote/issues/281#issuecomment-1564699039) where for each LSE traded sumbol, an additional lookup using the `SYMBOL_SEARCH` API is required to confidently set the currency used.

With API usage throttled to 5 calls per minute **by AlphaVantage**, this is definitely an annoyance for anyone who may use the AphaVantage module for LSE traded securities. So far the only one complaining is Wm-X. Others probably use another module to fetch pricing for those securities. 

Because he/she continues to act like a 5 year old and cannot play nice, Wm-X is blocked from the F::Q repository and his last few comments have been deleted. I tried to explain, with examples, that the issue is not as simple as he thinks it is. As for the AlphaVantage module, for now I think a CAVEAT section will be added to its POD with a short description of the currency issue with LSE traded securities.

Bruce S.

**Comment by Kaligula0** [comment]
Yeah, I got some spam emails since (s)he posted a few replies, that's why I came here to analyse the issue.

The complete solution would require:
- to check which stock exchanges have securities in different currencies
- the module to check if any securities in a call are from the exchanges mentioned above, and if yes then make an additional API call.. . which would be inconvenient, but reliable. 🤷‍♂️

**Comment by bpschuck** [comment]
> to check which stock exchanges have securities in different currencies and mark them in module's code

That is much easier said than done. One would need to know all the securities available from AlphaVantage, and then for each security check the trade currency. I've only been able to find a list of all US securities available from AV.

> the module to check if any securities in a call are from the exchanges mentioned above, and if yes then make an additional API call.. . which would be inconvenient, but reliable.

I'm not sure how many F::Q users may be using the AV method for fetching non-US traded securities. Effort vs reward. As I said previously, only one person thought it important enough to make a stink about it. So next time I am working on something I'll just add the CAVEAT I mentioned and be done with it. Now if someone else wants to spend the time and effort, they can have at it. That's the beauty of opensource. Seems the Wm-X person doesn't understand that. Just because I somehow became the current gatekeeper of getting F::Q releases pushed to CPAN, does not mean I am expected to fix issues reported for all the modules contributed by the community over the years. Hell, I especially don't care to even start looking at fixing AV since it may only help the person who has acted like a complete asshole. Maybe I should have said if he sends $100 in BTC to my crypto-wallet I'll be glad to work on it... 

So it will sit on hold for now. Who knows, AlphaVantage may even respond again to my email indicating the currency (and exchange which isn't even in the SYMBOL_SEARCH json) are now available.

Bruce S.

**Comment by bpschuck** [comment]
If throttling was not required, then adding a second call to fetch the currency for every quote would be relatively trivial. But because of the limitations of AV's free API key, adding that second call for all or select securities means reworking the throttling mechanism.

**Comment by Kaligula0** [comment]
> That is much easier said than done. (...) 

I completely understand that :) Just wanted to point out a possible solution for someone who will want to fix that, since that's what GitHub Issues module is for ;)

**Comment by bpschuck** [comment]
For those interested, please see the [Finance::Quote - AlphaVantage Trade Currencies ]( https://lists.gnucash.org/pipermail/gnucash-user/2023-July/107866.html) thread on the GnuCash-User email list. I think John R's idea of the user adding ".X" to symbols that they know AlphaVantage returns in GPb/GBX to cause the method to return the price data in GBP (GBX/100) is probably the simplest way to deal with this issue at this time. I will have a PR ready soon.
