### ISSUE TITLE
YahooJSON does not work for some shares

### ISSUE THREAD

**Issue by mumpitzstuff** [finance-quote/finance-quote#315]
A simple non working example is: [](https://query2.finance.yahoo.com/v11/finance/quoteSummary/MI9T.SG?modules=price,summaryDetail,defaultKeyStatistics)

In this case just price is available but no summaryDetail and no defaultKeyStatistics. The module does not check anything...
I would fix the module if i would know what i should do in case that these infos are not available. Should i return "" or should i not set $info for these values?

Another problem in my opinion is that $info{ $stocks, "last" }   = $json_price; and later on "last" is diveded by 100 in case of GBP or ZAc but the price keeps unchanged. Does not make sense to me. And what about the other prices like low, high and so on? I would bet all of them are returned in pence and not just the price. All in all the module is looking broken to me...

**Comment by bpschuck** [comment]
Thanks. Likely no one is really paying attention as long as their last/close is correct. Not also modifying low, high, open, etc. is probably an oversight of the module's original author.
If you could please just throw a few example symbols in the comments, that would be appreciated. While I now know a few LSE traded securities that are traded in GBx/GBp vs GBP, I am not familiar with any traded in ZAc (which I am guessing is fractional South African Rands?).

**Comment by bpschuck** [comment]
Also, modules are not required to return summary details or key statistics. In some modules, if the API or web scrape can determine values, they are returned. Some modules return not much more than the last traded price and currency, this does not mean they are broken.

**Comment by mumpitzstuff** [comment]
Hmm you are right. My expectation was that it will crash in case of an access to a undefined hash value, but it does not crash. Anyway i tried MI9T.SG and got no close value. But close is available for another json path... I will try to provide anything more useful the next days hopefully. Please be patient, i have a lot of other things to do... :)

**Comment by bpschuck** [comment]
@mumpitzstuff 
Thanks.
No hurry at all. No one else has raised an issue about ancillary values (such as close aka previous market close) not being available. Not sure what your plan is, but please avoid using different API fetches because that ancillary data is not available. If you know of a different Yahoo API (not the `/v11/finance/quoteSummary/$symbol?modules=price,summaryDetail,defaultKeyStatistics` currently used) that contains all or most of the desired data, please share it so I can also take a look.
With respect to the undef values, it may be cleaner to not even set the value in the returned hash if it was not available in the JSON. I'm on the fence on that one.

Thanks again.

Bruce S.

**Comment by jose-sanz** [comment]
Hi, I think the problem is the location from which we each call the Yahoo API. Using a VPN with a US IP I can get the same response as @bpschuck, but with a German IP I get a 404:
`{
	"finance": {
		"result": null,
		"error": {
			"code": "Not Found",
			"description": "HTTP 404 Not Found"
		}
	}
}`

**Comment by bpschuck** [comment]
Probably Yahoo starting to block access again. 
However, this is a different issue from this one. This issue is more about the data in JSON not being consistent for all securities. May have to open another issue for the Yahoo API returning 404s. Any yet may actually be the last straw for yahoo_json.

**Comment by bpschuck** [comment]
I added the "non-issue" label since this isn't an issue with the module and its parsing logic.  Instead it is because Yahoo does not provide the same data for stocks traded on different exchanges.
