### ISSUE TITLE
ASX doesn't return a date

### ISSUE THREAD

**Issue by ecocode** [finance-quote/finance-quote#63]
For gnucash to be able to use ASX.pm quotes it needs a date to be returned.

  ~/DEVELOPMENT/finance-quote >>> perl Examples/stockdump.pl ASX NAB                                                                                                                                        
  $VAR1 = {
            'NABlow' => '30.380',
            'NABp_change' => '0.000
  					 ',
            'NABbid' => '30.410',
            'NABopen' => '30.500',
            'NABprice' => '30.440',
            'NABsuccess' => 1,
            'NABlast' => '30.440',
            'NABhigh' => '30.550',
            'NABvolume' => '5508357',
            'NABnet' => '$0.000
  					 ',
            'NABsymbol' => 'NAB',
            'NABmethod' => 'asx',
            'NABcurrency' => 'AUD',
            'NABoffer' => '30.450',
            'NABexchange' => 'Australian Stock Exchange'
          };

**Comment by goodvibes2** [comment]
GnuCash will default the date to today if a date is not supplied from F::Q. From memory, this is done in gnc-fq-helper. There was a problem in gnc-fq-dump where it would incorrectly say that it could not use the quote if the date was not available but this was fixed several versions ago. Some-one has pointed out to me that a date is available from m.asx.com.au in another area of the webpage. I will investigate as soon as I can. For the moment, it appears the ASX website is struggling to service all the quote requests it is getting as it is only sometimes working. Could everyone please limit their ASX quote requests as much as possible!

**Comment by jusmop** [comment]
Hi goodvibes,

While it might be the intention for GnuCash to use today's date if the date not supplied by F::Q, for some reason it does not - at least when using ASX as a quote source. The current output of gnc-fq-dump is indeed fine as you point out, but GnuCash still returns an error when the source is set to ASX.

I read the bug report as ecocode suggesting that this should be fixed in F::Q, although you could argue that it should be fixed in GnuCash too.

gnc-fq-dump output on my system:

$ gnc-fq-dump ASX NAB
Finance::Quote fields Gnucash uses:
    symbol: NAB                  <=== required
      date: ** missing **        <=== recommended
  currency: AUD                  <=== required
      last: 30.570               <=\       
       nav:                      <=== one of these
     price: 30.570               <=/        
  timezone:                      <=== optional

** This quote will have today's date, which might be incorrect.
   GnuCash will use it, but you might prefer that it doesn't.

**Comment by frankcrawford** [comment]
Folks,
I'm currently working on a patch that includes the date in the output.  I'll probably try and generate a PR for it in the next few days.

Frank

**Comment by goodvibes2** [comment]
Hi jusmop,

GnuCash does work, at least for me, even though ASX.pm does not currently return a date.
I just proved it again in GnuCash 2.6.16, Windows 10 Finance::Quote 1.47. 
You can see gnc-fq-helper returns the date:
cd \Program Files (x86)\gnucash\bin
echo (asx "AMP" "ANZ" ) | perl gnc-fq-helper
(("AMP" (symbol . "AMP") (gnc:time-no-zone . "2017-11-17 08:18:31") (last . 5.120) (currency . "AUD"))
 ("ANZ" (symbol . "ANZ") (gnc:time-no-zone . "2017-11-17 08:18:31") (last . 29.290) (currency . "AUD")))

The ASX website seems to have a performance problem. In limited testing this morning, if I query 16 stocks at once, I have never seen it work. If I query 10 stocks at once, approx. 50% of the time it works. It usually works if I only query 1 or 2 stocks at once. Perhaps you are seeing this website performance problem, rather than GnuCash failing because there is no date returned by ASX.pm. Try unticking "Get Online Quotes" in the Security Editor for all stocks except 1.

It seems strange that I have only ever seen all stocks fail or all work in a single try. ASX.pm runs the webpage for each stock...

This performance problem of course makes the ASX pretty useless for anyone with more than a few stocks.

**Comment by jusmop** [comment]
Hi Chris,

Thanks for your email. I will test again tonight. FWIW I am running GnuCash
2.6.17 under Linux and Finance::Quote 1.47.

Can I ask exactly what your online source settings are for your ASX stocks
under Securities editor in GnuCash? I.e. is each stock source type set to
single source, multi- source, or unknown. And then what is the source
itself set to.

Thanks,
Justin.

**Comment by goodvibes2** [comment]
Hi Justin,
Example CBA
Security Information
 Symbol/abbreviation=CBA
 Display Symbol=CBA
 Type=ASX
Quote Source Information
 Type=Single
 Source=Australian Stock Exchange, AU
 Timezone=Use local time

**Comment by jusmop** [comment]
Yep same as me. Thanks.

**Comment by jusmop** [comment]
Hi Chris,

You are right. GnuCash does work with no dates when using ASX as a source.
I changed 3 stocks to ASX and GnuCash fetched prices fine.

Previously (after Yahoo was shutdown) I had changed 10+ stocks to ASX and
got consistent failures.

So I guess we want F::Q to fetch ASX quotes one a time...


Cheers,
Justin.

**Comment by frankcrawford** [comment]
Folks, FYI, I've just created a PR that will return the date of price data.

**Comment by goodvibes2** [comment]
frankcrawford's PR is https://github.com/finance-quote/finance-quote/pull/67 Unfortunately PR 67 is based on an ASX.pm which uses m.asx.com.au which stopped working approx 11 Feb 2018. There is a new url that may work: https://search.asx.com.au/s/search.html?query=CBA+BOQ&collection=asx-meta&profile=web - I will investigate shortly, after I have created a pull request to fix the perl warnings from yahooJSON.pm which currently causes GnuCash to hang in Windows when getting quotes for multiple (>15 in my case) stocks.

**Comment by goodvibes2** [comment]
PR https://github.com/finance-quote/finance-quote/pull/79 fixes date returned by yahooJSN.pm in Windows.
PR https://github.com/finance-quote/finance-quote/pull/82 modifies ASX.pm to work again but unfortunately there is no useful date/time available.

**Comment by fellen** [comment]
Chris, just an idea: can you get more than 10 quotes, if you insert a delay, i.e. 1s, after each query?

**Comment by jusmop** [comment]
Hi Frank,

I configured it for 4 queries per 65 seconds which has worked for me since
my previous post. It's slow but at least it works.

Cheers,
Justin.

**Comment by vincentl** [comment]
The ASX site does not appear to provide a date with the quote, so there is nothing more for the module to do.
